### PR TITLE
Fix Motion predict build issue

### PR DESCRIPTION
**Pull request by adev4a**
# PR Details
This PR fixes an issue introduced with https://github.com/usdot-fhwa-stol/carma-utils/pull/229 in the motion_predict package causing build errors. 
## Description
Fixes motion_predict package fails with a multiple definitions error being caused by the inclusion of the header in the multiple places.

image

## Types of changes

- [x] Defect fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that cause existing functionality to change)

## Checklist:

- [ ] I have added any new packages to the sonar-scanner.properties file
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING**](https://github.com/usdot-fhwa-stol/carma-platform/blob/develop/Contributing.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

File: motion_predict/include/motion_predict/motion_predict.hpp [hunk 1]
```diff
@@ -80,7 +80,8 @@ namespace cv{
 
     carma_perception_msgs::msg::PredictedState predictStep(const carma_perception_msgs::msg::PredictedState& obj, const double delta_t, const double confidence_drop_rate);
 
-    int64_t sec_to_nanosec = 1e9;
+    /*Constant for conversion from seconds to nanoseconds*/
+    const int64_t sec_to_nanosec = 1e9;
```
Comment (JonSmet) [inline motion_predict/include/motion_predict/motion_predict.hpp:84]: I think it would make sense to define this as `constexpr int64_t` instead?

**Review by JonSmet — CHANGES_REQUESTED** [review]

**Review by JonSmet — APPROVED** [review]
